/*

 BOOKMARK.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 3
   Tile set      : C:\gbdkDevResources\gbtd22\page_sel.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 102
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bookmark_h_INCLUDE
#define __bookmark_h_INCLUDE

#define bookmarkWidth 32
#define bookmarkHeight 3
#define bookmarkBank 0

extern const unsigned char bookmark[];

#endif

/* End of BOOKMARK.H */
